### PR TITLE
Update DocC deploy to use macOS 15 + Xcode 16.1

### LINKED ISSUE #585: Update DocC deployment to use macOS 15 + Xcode 16.1
We should keep this workflow macOS/Xcode usage in sync with CI

### PR DESCRIPTION
**Pull request by andrewdmontgomery**
### Description

This updates the DocC deployment to use the same version of macOS and Xcode that we are using in CI.

### Testing Steps

- [ ] CI should be 🟢 
- [x] The documentation workflow should run successfully

### CODE REVIEW

**Comment by andrewdmontgomery** [comment]
image

**Comment by andrewdmontgomery** [comment]
Wait.  I rebased this on `release/3.1.0` and pushed, then retargeted the PR to that branch.  But now there are extra commits.  I'm going to mark this "Draft" while I sort that out.

**Comment by andrewdmontgomery** [comment]
Fixed

**Comment by andrewdmontgomery** [comment]
This should target `trunk`, not the release.  I've rebased, retargeted, etc.

**Review by etoledom — APPROVED** [review]
Thank you! 🙏

**Pull request merged**
