### PR TITLE
Rename `Gravatar-Demo` --> `UIKit-Demo`, `Gravatar-SwiftUI-Demo` --> `SwiftUI-Demo`

### PR DESCRIPTION
**Pull request by andrewdmontgomery**
Closes #

### Description

This makes a few changes in preparation for being able to publish Prototype builds of our Swift and SwiftUI demo apps.  It also adds separate AppIcons for each target.

Note that this also updates the bundleId's so that they can be easily distinguished and mapped to the appropriate targets.

It also corrects a filename error:
```diff
- Gravatar-SwiftUI-Demo.Base.xcconfig.xcconfig
+ Gravatar-SwiftUI-Demo.Base.xcconfig
```

_Edit: I ended up renaming the xcconfigs to match the Scheme names._

### CODE REVIEW

**Comment by andrewdmontgomery** [comment]
@etoledom @pinarol

**Review by mokagio — APPROVED** [review]
LGTM

(Thanks for the `xcconfig.xcconfig` fix also)

Have you considered renaming the folders as well? I think if the rename is dove via Xcode, all the reference in the project file will update automatically.

**Comment by mokagio** [comment]
> Have you considered renaming the folders as well? I think if the rename is dove via Xcode, all the reference in the project file will update automatically.

@andrewdmontgomery I'm going to merge this as is so there won't be conflicts when I'll edit the `xcconfig`s later. 

The folder rename can happen later, if agreed. And I'd be happy to do it myself while I'm in that part of the code.

**Comment by andrewdmontgomery** [comment]
Thanks @mokagio .  I'll address your question about folders in the main PR.

**Pull request merged**
