### PR TITLE
Changing icons of demo app

### PR DESCRIPTION
**Pull request by etoledom**
### Description

Proposing different icons for the demo app:

CleanShot 2024-07-25 at 16 28 47@2x

The idea is that they represent the skeleton of a Gravatar card, using the color schemes of UIKit and SwiftUI.

### CODE REVIEW

**Review by pinarol — APPROVED** [review]
Looks awesome to me! 🎉 
@andrewdmontgomery WDYT?

**Comment by andrewdmontgomery** [comment]
I love that for SwiftUI, since SwiftUI uses the Blue/Black color palette.  Can we use the Orange/White palette (of Swift) for UIKit?

The main reason for me is here: 
image

I know Gravatar's color is blue.  But the `G` icon within the App Icon conveys "this is Gravatar" very well.  We can use color to differentiate the important difference.

**Comment by etoledom** [comment]
@andrewdmontgomery - @pinarol - Updated!

CleanShot 2024-07-26 at 09 36 25@2x

**Review by pinarol — APPROVED** [review]
Even more awesomeness 🎉

**Pull request merged**
