### PR TITLE
Update to XCode 16.2

### PR DESCRIPTION
**Pull request by pinarol**
Closes #

### Description

Makes configuration changes to start using XCode 16.2

### Testing Steps

CI green.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
I'm ready for the switch.

Let's wait for @andrewdmontgomery before merging also 👍

**Comment by pinarol** [comment]
We can't merge yet since the CI isn't ready yet.

**Comment by andrewdmontgomery** [comment]
https://appsinfrap2.wordpress.com/2024/12/17/xcode-16-2-available-in-ci/

I'll make the change

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
